extends:
  - "@35up/35up-base"
rules:
  '@typescript-eslint/naming-convention':
    - 'warn'
    -
      selector:
        - 'enum'
        - 'enumMember'
      format:
        - 'UPPER_CASE'
    -
      selector:
        - 'typeAlias'
      format:
        - 'StrictPascalCase'
    -
      selector:
        - 'variable'
        - 'function'
        - 'parameter'
        - 'method'
        - 'classProperty'
        - 'typeProperty'
      format:
        - 'strictCamelCase'
    -
      selector:
        - 'variable'
        - 'function'
        - 'parameter'
        - 'method'
        - 'property'
      modifiers:
        - 'requiresQuotes'
      format: null
    -
      selector:
        - 'variable'
      modifiers:
       - 'const'
      format:
        - 'strictCamelCase'
        - 'UPPER_CASE'
    -
      selector:
        - 'class'
      format:
        - 'StrictPascalCase'
    -
      selector:
        - 'parameter'
      modifiers:
        - 'unused'
      leadingUnderscore: 'allowSingleOrDouble'
      format: null
